services:
  hetzner-base:
    build:
      context: .
      dockerfile: hetzner-base.Dockerfile
    image: cluster-hetzner-base

  spark-master:
    build:
      context: .
      dockerfile: spark-cluster.Dockerfile
    container_name: spark-master
    environment:
      - SPARK_WORKLOAD=master
      - SPARK_MASTER_PORT=7077
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ./workspace:/opt/workspace
    depends_on:
      - hetzner-base

  spark-worker-1:
    build:
      context: .
      dockerfile: spark-cluster.Dockerfile
    container_name: spark-worker-1
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - ./workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    build:
      context: .
      dockerfile: spark-cluster.Dockerfile
    container_name: spark-worker-2
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8082
    ports:
      - "8082:8082"
    volumes:
      - ./workspace:/opt/workspace
    depends_on:
      - spark-master

  
  spark-worker-3:
    build:
      context: .
      dockerfile: spark-cluster.Dockerfile
    container_name: spark-worker-3
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8083
    ports:
      - "8083:8083"
    volumes:
      - ./workspace:/opt/workspace
    depends_on:
      - spark-master